# Generated by Django 6.1 on 2026-09-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_noms_francais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-cree_le']},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['categorie', 'nom']},
        ),
        migrations.AlterField(
            model_name='articlecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='shop.commande'),
        ),
    ]
